# Generated by Django 2.2.2 on 2019-07-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190728_0157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodstype',
            table='df_goods_type',
        ),
    ]
